### ISSUE TITLE
Issue with relationships

### ISSUE THREAD

**Issue by andrew13** [summerstreet/woodling#2]
I attempted this

```
Woodling::seed('Weakness', function($weakness)
{
    $weakness->type = 'Fruit';
    $weakness->name = 'Apple';
});

Woodling::seed('Person', function($person)
{
    $person->name = 'Eve';
    $person->weakness = Woodling::retrieve('Weakness');
});

$eve = Woodling::retrieve('Person');
```

and i'm getting an error:

```
PHP Fatal error:  Cannot redeclare class Illuminate\Support\Str in /var/www/sites/sample-app/bootstrap/compiled.php on line 5435
PHP Stack trace:
PHP   1. {main}() /usr/bin/phpunit:0
PHP   2. PHPUnit_TextUI_Command::main() /usr/bin/phpunit:46
PHP   3. PHPUnit_TextUI_Command->run() /usr/share/php/PHPUnit/TextUI/Command.php:130
PHP   4. PHPUnit_TextUI_Command->handleArguments() /usr/share/php/PHPUnit/TextUI/Command.php:139
PHP   5. PHPUnit_TextUI_Command->handleBootstrap() /usr/share/php/PHPUnit/TextUI/Command.php:620
PHP   6. PHPUnit_Util_Fileloader::checkAndLoad() /usr/share/php/PHPUnit/TextUI/Command.php:867
PHP   7. PHPUnit_Util_Fileloader::load() /usr/share/php/PHPUnit/Util/Fileloader.php:79
PHP   8. include_once() /usr/share/php/PHPUnit/Util/Fileloader.php:95
PHP   9. require() /var/www/sites/sample-site/bootstrap/autoload.php:32
```

I only get this error when trying the relationships.

**Comment by rkrv** [comment]
Do you have `Weakness` and `Person` classes defined? Which version of Laravel are you using?

**Comment by andrew13** [comment]
Check out: https://github.com/andrew13/Laravel-4-Bootstrap-Starter-Site/blob/master/app/tests/blueprints/User.php

If you uncomment the commented lines it'll break.

**Comment by travisolbrich** [comment]
I'm having the same issue. Does anyone have a fix?

**Comment by rkrv** [comment]
I'm working on it. I think I know what's the reason but I'm doing more tests. If I'm lucky, the fix will be up today.

**Comment by rkrv** [comment]
Okay guys, this is a huge mistake on my part. I documented the relationship usage wrong. To retrieve a relationship, you should use a lazy attribute like so:

``` php
Woodling::seed('Person', function($person)
{
    $person->name = 'Eve';
    $person->weakness = function() { return Woodling::retrieve('Weakness'); };
});
```

The reason you have to do this is because blueprint is constructed at the load time when it's seeded (in order to save resources during the testing) and when you don't use the lazy attribute it just can't find the relation blueprint. I am updating the docs and bumping up the version number. Huge apologies about this.

@andrew13 In order to fix your issue use

``` php
$blueprint->role = function() { return Woodling::retrieve('RoleAdmin'); };
```

for `UserAdmin` and

``` php
$blueprint->role = function() { return Woodling::retrieve('RoleComment'); };
```

for `UserUser`.

**Comment by travisolbrich** [comment]
Thanks!
