### ISSUE TITLE
Difference between Woodling::retrieve and Woodling::save

### ISSUE THREAD

**Issue by tomekowal** [summerstreet/woodling#8]
I am not exactly sure, if it is an issue or if I misunderstood the docs. I've already reported the issue to stackoverflow.
http://stackoverflow.com/questions/29719536/difference-between-woodlingsaved-and-woodlingretrieve

**Comment by rkrv** [comment]
`Woodling::retrieve` creates an instance of your model, which is not persisted to your storage engine. `Woodling::save` simply calls `Woodling::retrieve` and then calls `save` on the retrieved instance. It doesn't cleanup after itself, so all persisted entries should be visible in your database. If they are not visible, perhaps there is a problem in your database configuration?

**Comment by tomekowal** [comment]
I've found the issue. My model did not pass Ardent validation rules. This gave me silent error in `Ardent::save` and `Model::save` was never called. It seems, that everything is correct with your library. 

`save` returns false, if something went wrong. Maybe it would be good idea to throw error, when `save` returns false? If you like it, I can make a pull request.

**Comment by tomekowal** [comment]
Hi! The pull request, I created resolves the issue. It includes unit tests and doesn't change the API. If there is something, you would like me to change before merging - just let me know.

**Comment by rkrv** [comment]
Hey, thank you for your pull request. Woodling is framework agnostic, so we can't expect that all `save()` methods in the wild will return `false` if they fail to persist to the database. It is also not Woodling's responsibility to validate that underlying code performs it's task. Due to these reasons, I can't accept your pull request. Thank you again for your time.

**Comment by tomekowal** [comment]
No problem, I just assumed, that returning false on failed save is a convention. In that case, I am closing the pull request. Thanks for your time reviewing it!
